### ISSUE TITLE
other archivematica docker distributions

### ISSUE THREAD

**Issue by jhsimpson** [ualibraries/archivematica#1]
Hi, this looks really interesting.  Would it be okay for us to link to this repo from https://wiki.archivematica.org? 

You might be interested in looking at a couple of other repositories that create an Archivematica distribution using Docker. 

https://github.com/artefactual-labs/am.git
This is beinig used as the default development environment by most Archivematica developers at the moment.  It uses docker-compose and puts the different components of Archivematica into separate containers.

https://github.com/JiscRDSS/rdss-archivematica
Jisc are a UK based organization that are running Archivematica in research data management shared service.  This repo has a docker-compose based deploy method, and also has a couple of aws specific deployment methods, one based on docker-compose + docker-machine, the other using terraform.  Both of the aws specific methods in that repo are untested, iirc.  This repo adds other components to the default Archivematica stack, notably support for Shibboleth based integration and a NextCloud instance.

**Comment by ghost** [comment]
Hi, we are no longer using this repository.
